version: "3.8"

services:
  web1:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: node server.js

  web2:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: node server.js
